language: python

python:
  - "3.5"

sudo: required
dist: trusty

services:
  - docker

before_install:
  - sudo /etc/init.d/mysql stop
  - sudo apt-get update
  - git clone https://github.com/FAForever/faf-stack.git faf-stack
  - pushd faf-stack
  - git checkout 6c09957b6671980b4d1ad0016bd2316d75cfffeb
  - cp .env.template .env
  - cp -r config.template config
  - scripts/init-db.sh
  - wget https://raw.githubusercontent.com/FAForever/db/`grep -oP 'faforever/faf-db-migrations:\K(.*)$' ./docker-compose.yml`/test-data.sql
  - docker exec -i faf-db mysql -uroot -pbanana faf < test-data.sql
  - popd
  - python -m pip install coveralls

install:
  - cp faf-server.example.pem faf-server.pem
  - docker build -t faf-python-server .

script:
  - docker run --name faf-python-server --link faf-db:db -e FAF_DB_PASSWORD=banana -e FAF_DB_NAME=faf faf-python-server bash scripts/run_tests_with_coverage.sh
  - docker cp faf-python-server:/code/.coverage .coverage
  - sed -i.bak s#/code/#$(pwd)/#g .coverage
  - coveralls

after_success:
  - export REPO=faforever/faf-python-server
  - if [ -n "${TRAVIS_TAG}" ]; then
      docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}";
      docker tag faf-python-server ${REPO}:${TRAVIS_TAG};
      docker push ${REPO};
    fi
